### Numpy Exercises
https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md

https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
#1 import numpy as np

import numpy as np

In [7]:
#2 checking the version of numpy
np.__version__

'1.22.4'

In [11]:
#3 creating a null vector of size 10

arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#4 Find the memory size of any array
arr.size

10

In [21]:
#5 documentation of numpy add function from command line
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [22]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [34]:
#6 Create a null vector of size 10 but the fifthe value is 1

arr = np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [38]:
#7 create a vector having values ranging from 10 to 49

arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [60]:
#8 reversing a vector.
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])


In [61]:
arr[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [64]:
for i in range(0,arr.size//2):
    r=arr[i]
    arr[i]=arr[-1-i]
    arr[-1-i]=r
    
arr    

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
#9 Create a 3X3 matrix having values from 0 to 8
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
#10 find the indices of non zero elements in a given array
arr = np.array([1,2,0,0,4,0])
np.where(arr!=0)

(array([0, 1, 4], dtype=int64),)

In [75]:
#11 3x3 identity matrix
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
#12 3x3x3 array with random values

arr = np.random.random((3,3,3))
arr

array([[[0.78499211, 0.55927214, 0.24211751],
        [0.53353933, 0.09736263, 0.69408456],
        [0.68933353, 0.3905873 , 0.39385413]],

       [[0.44045428, 0.5240342 , 0.8234831 ],
        [0.33635082, 0.33370265, 0.8247893 ],
        [0.37927771, 0.91088183, 0.38249952]],

       [[0.62274997, 0.83034767, 0.14823215],
        [0.13310909, 0.67495849, 0.4842119 ],
        [0.04840128, 0.65012347, 0.92873525]]])

In [174]:
#13 Create 10x10 array with random values and find the max and min values
arr = np.random.randint(100,size=(10,10))
arr

array([[51, 98, 49, 86, 49,  8, 91, 35, 60, 92],
       [78, 17, 95, 81, 76, 80, 10, 42, 61, 15],
       [72, 17, 55, 87,  5, 35, 60, 43, 17,  4],
       [56, 58, 22, 20, 43, 69, 72, 82, 76, 94],
       [92, 62, 28, 68, 13, 16, 70, 99, 92, 66],
       [47, 98, 49, 36, 16, 61, 88, 48, 72, 44],
       [36, 50, 21, 20, 70, 44, 79,  7, 19, 80],
       [90, 29, 93, 49, 55, 19, 80, 71, 41, 27],
       [28, 14, 14, 55, 66, 85, 23, 91, 73,  9],
       [39, 94, 86,  4, 97, 64, 51, 58, 96, 17]])

In [100]:
arr.max()

97

In [101]:
arr.min()

1

In [102]:
np.where(arr.max())

(array([0], dtype=int64),)

In [112]:
#14 Find the mean of the vector of random no.s
arr = np.random.randint(100,size=(1,30))
arr

array([[39, 44, 70, 14, 53, 81, 51, 47, 94, 96, 97, 99, 68, 45, 45, 82,
        15, 20,  6, 32,  5, 79, 48, 76, 69, 32, 29, 75, 35, 85]])

In [113]:
np.mean(arr)

54.36666666666667

In [161]:
#15 create a 2D array with 1 on the border and 0 inside
arr = np.ones((5,5))
arr[1:-1,1:-1]=0

In [162]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [163]:
#16 add a border of zeroes to existing array
arr = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [133]:
#17 Implement the following expressions
0*np.nan
np.nan == np.nan
np.inf>np.nan
np.nan-np.nan
np.nan in set([np.nan])
0.3 ==3*0.1

False

In [171]:
#18 Create 5x5 matrix with values 1,2,3,4 just below the diagonal
arr = np.diag(1+np.arange(4),k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [172]:
#19 Create a 8X8 checker board
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2]=1
arr[::2,1::2]=1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [182]:
#20 consider a (6,7,8) shape array, what is he index(x,y,z) of the 100th element
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [183]:
np.info(np.unravel_index)

 unravel_index()

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unrave